#!/usr/bin/env python

import subprocess
import xml.etree.ElementTree as ET
import socket

hostname = socket.gethostname()

out = subprocess.check_output(['nvidia-smi', '-q', '-x'])
root = ET.fromstring(out)

for gpu in root.iter('gpu'):
        ident = '%s/cuda-%s' % (hostname, gpu.attrib['id'])

        fanspeed = float(gpu.find('fan_speed').text.split()[0])
        print 'PUTVAL %s/fanspeed %f' % (ident, fanspeed)

        temp = float(gpu.find('temperature/gpu_temp').text.split()[0])
        print 'PUTVAL %s/temperature %f' % (ident, temp)

        memused = float(gpu.find('memory_usage/used').text.split()[0])
        print 'PUTVAL %s/memory %f' % (ident, memused*1e6)

